import type { Metadata } from "next";
import './global.css'
import { Aeonik } from "./fonts";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";
import { Providers } from "./Providers";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Norma AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
    <body className={`${Aeonik.variable} antialiased relative`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
